# Generated by Django 2.2.6 on 2019-10-22 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_coursestag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursestag',
            options={'verbose_name': '课程标签', 'verbose_name_plural': '课程标签'},
        ),
    ]
