# Generated by Django 2.2.4 on 2019-08-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(max_length=18, verbose_name='年龄'),
        ),
    ]
