# Generated by Django 2.2.4 on 2019-08-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20190812_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(verbose_name='年龄'),
        ),
    ]
