# Generated by Django 2.2.4 on 2019-08-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20190812_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='work_position',
            field=models.CharField(max_length=50, verbose_name='职位'),
        ),
    ]
