# Generated by Django 2.2.6 on 2019-10-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_auto_20191014_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_gold',
            field=models.BooleanField(default=False, verbose_name='是否金牌'),
        ),
    ]
